rec_test:
	g++ test_data_io.cpp -g -lbluetooth -lpthread -lsqlite3 -o test_data_io.out
	./test_data_io.out

send_test:
	g++ test_comm.cpp -g -lbluetooth -lpthread -o test_comm.out
	./test_comm.out DC:A6:32:33:BD:F1
