Make:
	g++ test.cpp -lbluetooth -g -o main.out
	./main.out

client:
	g++ test_client.cpp -lbluetooth -g -o test_client.out
	./test_client.out

server:
	g++ test_server.cpp -lbluetooth -g -o test_server.out
	./test_server.out